"""
Django settings for mein_projekt project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""
from pathlib import Path										# Importiert Path, um betriebssystemunabhaengige Dateipfade zu bauen

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent							# BASE_DIR zeigt auf das Hauptverzeichnis des Projekts, Wird spaeter fuer Datenbank, Templates und statische Dateien genutzt

# Security
SECRET_KEY = 'django-insecure-=kzu_cr1emkk$f#$c7u0!)iz4-bfjgb5bbp4k1z(03nc-17+qw'			# Geheimer Schluessel fuer Verschluesselung (Sessions, Tokens, Passwoerter)
DEBUG = True												# DEBUG=True zeigt detaillierte Fehlermeldungen (NUR Entwicklung)

ALLOWED_HOSTS = [	
   "[2001:7c0:2320:2:f816:3eff:fe38:d98d]",
]													# Liste der Hosts, die auf das Projekt zugreifen duerfen

# Applications
INSTALLED_APPS = [
   'django.contrib.admin',										# Admin-Oberflaeche von Django
   'django.contrib.auth',										# Authentifizierung und Benutzerverwaltung
   'django.contrib.contenttypes',									# Basis fuer Models und Datenbanktypen
   'django.contrib.sessions',										# Session-Verwaltung (Login-Zustaende)
   'django.contrib.messages',										# Systemmeldungen (z.B. Erfolgs- oder Fehlermeldungen)
   'django.contrib.staticfiles',									# Verwaltung statischer Dateien (CSS, JS, Bilder)
   'meine_app',												# unsere eigene Django-App des Projekts
]													 


# Sessions
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'					# Sessions werden in signierten Cookies gespeichert (keine DB-Tabelle noetig)

# Middleware
MIDDLEWARE = [
   'django.middleware.security.SecurityMiddleware',							# Sicherheitsrelevante HTTP-Header
   'django.contrib.sessions.middleware.SessionMiddleware',						# Ermoeglicht Zugriff auf Sessions
   'django.middleware.common.CommonMiddleware',								# Standard-HTTP-Funktionen (z.B. Redirects)
   'django.middleware.csrf.CsrfViewMiddleware',								# Schutz vor CSRF-Angriffen bei Formularen				
   'django.contrib.auth.middleware.AuthenticationMiddleware',						# Verknuepft Requests mit dem eingeloggten Benutzer
   'django.contrib.messages.middleware.MessageMiddleware',						# Erlaubt Nachrichten zwischen Requests
   'django.middleware.clickjacking.XFrameOptionsMiddleware',						# Schutz vor Clickjacking
]

# URLs and Templates
ROOT_URLCONF = 'mein_projekt.urls'									# Gibt an, wo die zentrale URL-Konfiguration liegt
TEMPLATES = [
   {
       'BACKEND': 'django.template.backends.django.DjangoTemplates',					# Template-Engine von Django
       'DIRS': [
           BASE_DIR / 'mein_projekt' / 'meine_app' / 'templates',					# Ordner, in dem globale HTML-Templates liegen
       ],
       'APP_DIRS': True,										# Django sucht automatisch in templates-Ordnern der Apps
       'OPTIONS': {
           'context_processors': [
               'django.template.context_processors.request',						# Stellt request im Template zur Verfuegung
               'django.contrib.auth.context_processors.auth',						# Stellt Benutzerinformationen bereit
               'django.contrib.messages.context_processors.messages',					# Stellt Messages im Template bereit
           ],
       },
   },
]
WSGI_APPLICATION = 'mein_projekt.wsgi.application'							# Einstiegspunkt fuer Webserver (Apache)

# Database
DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.sqlite3',								#sicherheit für Django
       'NAME': BASE_DIR / 'db.sqlite3',
   }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
   {
       'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',		# Verhindert aehnliche Passwoerter wie Benutzername
   },
   {
       'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',			# Mindestlaenge fuer Passwoerter
   },
   {
       'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',			# Verhindert sehr haeufige Passwoerter
   },
   {
       'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',			# Verhindert nur numerische Passwoerter
   },
]

# Internationalization
LANGUAGE_CODE = 'en-us'											# Standardsprache der Anwendung
TIME_ZONE = 'UTC'											# Zeitzone fuer Datums- und Zeitangaben									
USE_I18N = True												# Aktiviert internationale Sprachunterstuetzung
USE_TZ = True												# Aktiviert Zeitzonen-Unterstuetzung

# Static files
STATIC_URL = 'static/'											# URL-Pfad fuer statische Dateien
STATICFILES_DIRS = [
   BASE_DIR / 'static',
]													# Ordner fuer statische Dateien im Entwicklungsmodus
STATIC_ROOT = '/var/www/static'										# Zielordner fuer collectstatic



LOGIN_URL = 'login'											# URL, zu der nicht eingeloggte Benutzer umgeleitet werden
LOGIN_REDIRECT_URL = 'uebersicht'									# Zielseite nach erfolgreichem Login
LOGOUT_REDIRECT_URL = 'login'										# Zielseite nach Logout


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'							# Standardtyp fuer Primaerschluessel in der Datenbank